[scconfig] -Fix: use hand written Makefile for installing icons in data/
git-svn-id: svn://repo.hu/pcb-rnd/trunk@142 1d61de99-560f-4dba-8957-1e505d42358b

diff --git a/data/icon-theme-installer b/data/icon-theme-installer
--- a/data/icon-theme-installer
+++ b/data/icon-theme-installer
@@ -103,15 +103,15 @@ if test -z "$INSTALL_BASE_DIR"; then
 	exit 1
 fi
 
-if test ! -x `echo "$MKINSTALLDIRS_EXEC" | cut -f1 -d' '`; then
-	echo "Cannot find '$MKINSTALLDIRS_EXEC'; You probably want to pass -m \$(mkinstalldirs)"
-	exit 1
-fi
+#if test ! -x `echo "$MKINSTALLDIRS_EXEC" | cut -f1 -d' '`; then
+#	echo "Cannot find '$MKINSTALLDIRS_EXEC'; You probably want to pass -m \$(mkinstalldirs)"
+#	exit 1
+#fi
 
-if test ! -x `echo "$INSTALL_DATA_EXEC" | cut -f1 -d' '`; then
-	echo "Cannot find '$INSTALL_DATA_EXEC'; You probably want to pass -x \$(INSTALL_DATA)"
-	exit 1
-fi
+#if test ! -x `echo "$INSTALL_DATA_EXEC" | cut -f1 -d' '`; then
+#	echo "Cannot find '$INSTALL_DATA_EXEC'; You probably want to pass -x \$(INSTALL_DATA)"
+#	exit 1
+#fi
 
 if test -z "$SRC_DIR"; then
 	SRC_DIR=.
